### PR TITLE
Rework header logo nav

### PR DESCRIPTION
**Pull request by john12321**
- Redo header/nav using latest [React comps](https://main--6422e711d7f854c1b681c505.chromatic.com/?path=/docs/components-header--docs)
- Separate main app nav from settings/config stuff (e.g. MFA set-up) and Support (using [NHS app layout](https://www.nhs.uk/nhs-app/) as a guide). 
Note: This is just the start of the process to separate concerns. Also the Support and MFA set-up cards are still on the Home page for now.

ps. This PR has your name on it @ReubenRobertsHEE; checkout the number of file changes! (mostly purging stuff tbf) .
pps. Was so tempted to 'boy scout' the Amplify state management 😅
 
 TIS21-5285

### CODE REVIEW

**Comment by ReubenRobertsHEE** [comment]
800 lines of churn to change a header, @john12321 ? I thought these frameworks were supposed to make you less verbose 😈

**Comment by john12321** [comment]
> 800 lines of churn to change a header, @john12321 ? I thought these frameworks were supposed to make you less verbose 😈
> 
> My man, we've got to find a better way to separate out tech-debt from dev - Andy focusses on raising back-end tech-debt tickets, maybe you could do the same for the (lonely!) front-end dev? 😀

🤣 @ReubenRobertsHEE There's relatively little tech debt in this one. The vast bulk of the changes s using the new react header stuff which then leads to editing comps/ deleting redundant comps (in addition to other things like renaming HEE comps etc. which you could argue could later I suppose) . Happy to go through the changes/reasons for them if you like?

**Comment by ReubenRobertsHEE** [comment]
image

**Comment by ReubenRobertsHEE** [comment]
All looks good to me. Only this is when you click the NHS England logo, you get a brief period with a strange effect (see above). 🤷

**Comment by john12321** [comment]
> All looks good to me. Only this is when you click the NHS England logo, you get a brief period with a strange effect (see above). 🤷 . Is that part of the new NHS England styling?

Cheers @ReubenRobertsHEE , yeah this is the default active state using the `className="nhsuk-header__logo"` class but has gone a bit weird (for a second before the page reloads) because of our custom NHS England logo wrapped in the anchor. If we went for the built-in `Header.Logo` comp then this takes care of all the CSS for different states (but only gives us the NHS logo minus the England text) :

` render: () => <Header>
      <Header.Container>
        <Header.Logo href="/" />
        <Header.Content>
          <Header.MenuToggle />
        </Header.Content>
      </Header.Container> ...`
    
Might be worth having a hack around/follow-up PR unless you think it's too fugly to merge?

**Comment by john12321** [comment]
@ReubenRobertsHEE last 2 commits give us this (consistent with our current bespoke active nav states):

image

**Comment by ReubenRobertsHEE** [comment]
Sounds good @john12321 - any reason for the slight colour change between the 'England' background and the rest of the banner? Or is it just my eyes 👓 !

**Review by ReubenRobertsHEE — APPROVED** [review]

**Comment by john12321** [comment]
Cheers @ReubenRobertsHEE , just a small matter of the e2e tests now...💣

**Pull request merged**
