### PR TITLE
feat: placement action notifications

### PR DESCRIPTION
**Pull request by ReubenRobertsHEE**
Just slip-streaming on from Doris's work 🌮  😅 

TIS21-5621
TIS21-5622

### CODE REVIEW

**Comment by john12321** [comment]
@ReubenRobertsHEE join the queue, my friend. v0.91 is taken 😂 
I'm on leave for a week soon so happy to close my PR til I get back if that makes things easier?
(Also Doris's commit threw up an e2e test fail so no movement atm.)

**Comment by ReubenRobertsHEE** [comment]
@john12321 well, enjoy your leave 🌴 . Maybe leave your PR active - if we can figure out that e2e test fail, hopefully we can unblock the queue as it stands

**Comment by john12321** [comment]
@ReubenRobertsHEE Very kind of you, sir. 
Looking forward to all those DIY jobs I've put off for the last couple of months. 
Doris shared some screenshots of the failing test; looks like it's stuck on section 2 (panel errors) which is preventing the nav to submit and finding those declaration checkboxes. She's rolled back versions but gets the same error so nothing to do with new changes. Stage data changes perhaps? 🤷‍♂️

**Review by DorisWongNHS — DISMISSED** [review]
Approved as Placement actions displayed and completed fine on my local.
The blocked E2E test is now resolved. It was due to the extra works in section2 without training post stopped the test moving forward. It was fixed by data cleaning. John's and this branch can be merge when they are ready.

**Review by DorisWongNHS — APPROVED** [review]

**Pull request merged**
