### PR TITLE
Remove phone_number attribute when swapping MFA type from SMS to TOTP

### PR DESCRIPTION
**Pull request by john12321**
- Remove phone_number attribute when swapping MFA type from SMS to TOTP.
- Order the actions so the phone_number removal is the last action in TOTP set-up process just in case process is aborted.
- Refactor some mfa comps

TODO 
- (see https://github.com/Health-Education-England/tis-trainee-ui/pull/680 )
- refactor redux slices to make DRY
- look at ways to increase test coverage for sign-up/MFA 
 
TICKET TIS21-3193

### CODE REVIEW

**Comment by ReubenRobertsHEE** [comment]
For what it's worth, it all looks ok to me 😁 . Just wondering, though: is it possible to actually include a test that the phone number has been removed when switching from SMS to TOTP? I'm thinking something like possibly an end-to-end(?) test of 'set up user with SMS authentication and phone number, trigger change from SMS to TOTP, retrieve user details from cognito, see that there is now no phone number'. I don't know if this is excessive in relation to the other tests, or if I've missed something where it is already tested!

**Comment by john12321** [comment]
> For what it's worth, it all looks ok to me 😁 . Just wondering, though: is it possible to actually include a test that the phone number has been removed when switching from SMS to TOTP? I'm thinking something like possibly an end-to-end(?) test of 'set up user with SMS authentication and phone number, trigger change from SMS to TOTP, retrieve user details from cognito, see that there is now no phone number'. I don't know if this is excessive in relation to the other tests, or if I've missed something where it is already tested!

Hi @ReubenRobertsHEE , cheers for the feedback! Yeah this is the main gap in the MFA testing. We haven't got/can't set up the e2e infra for the TOTP journey even before getting to the point of checking the user pool phone_number attribute. For example,  for an e2e test, I think we would need a way of reading the newly-generated QR code to add 'HEE TIS Self-Service' account, key in the 6-digit code from that linked account and then do the checking in the user pool. Not sure how to do this. Any ideas gratefully received! 😄

**Review by Judge40 — APPROVED** [review]

**Comment by Judge40** [comment]
> > For what it's worth, it all looks ok to me 😁 . Just wondering, though: is it possible to actually include a test that the phone number has been removed when switching from SMS to TOTP? I'm thinking something like possibly an end-to-end(?) test of 'set up user with SMS authentication and phone number, trigger change from SMS to TOTP, retrieve user details from cognito, see that there is now no phone number'. I don't know if this is excessive in relation to the other tests, or if I've missed something where it is already tested!
> 
> Hi @ReubenRobertsHEE , cheers for the feedback! Yeah this is the main gap in the MFA testing. We haven't got/can't set up the e2e infra for the TOTP journey even before getting to the point of checking the user pool phone_number attribute. For example, for an e2e test, I think we would need a way of reading the newly-generated QR code to add 'HEE TIS Self-Service' account, key in the 6-digit code from that linked account and then do the checking in the user pool. Not sure how to do this. Any ideas gratefully received! 😄

It would be great to be able to do automate it, I have no idea how we would start though. The effort vs reward doesn't feel great with what we know so far.

**Review by ReubenRobertsHEE — APPROVED** [review]
Good to have a wider tech discussion around how to get the best out of the testing frameworks for this, as we chatted about 👍

**Pull request merged**
